### ISSUE TITLE
Annotations on non-dynamic nodes

### ISSUE THREAD

**Issue by alessiostalla** [LionWeb-io/lionweb-java#153]
Currently, it is only possible to add annotations on dynamic nodes because the _annotations_ collection is an immutable view and the _addAnnotation_ method is only available on _AbstractClassifierInstance_ objects.

**Comment by ftomassetti** [comment]
Oh, that is not great. I guess that `DynamicNode` should extend `AbstractClassifierInstance`

**Comment by ftomassetti** [comment]
I plan to look into this tomorrow

**Comment by ftomassetti** [comment]
Which nodes have you encountered that were not extending `DynamicNode` or `AbstractClassifierInstance`?

**Comment by ftomassetti** [comment]
Or do you think that `addAnnotation` should go directly on `Node`?
So far `Node` is about making nodes readable, and not writable but perhaps that is inconvenient

**Comment by alessiostalla** [comment]
> Which nodes have you encountered that were not extending `DynamicNode` or `AbstractClassifierInstance`?

None, because I've used this in the context of Kolasu import/export which uses dynamic nodes. 

> Or do you think that addAnnotation should go directly on Node?
> So far Node is about making nodes readable, and not writable but perhaps that is inconvenient

I don't know, because I miss the grand design picture. My gut feeling is that an annotation is something you may want to add to a node independently of the creator of the node. Also I see that `Node` being a `ClassifierInstance` has `setPropertyValue` and `setReferenceValues` methods that mutate it (but nothing for containments?). Maybe `addAnnotation` should go in `ClassifierInstance`?

**Comment by ftomassetti** [comment]
Thank you Alessio, you raise good points.
I think we should indeed add this method to `ClassifierInstance`. If some `Node` is read-only it could always throw an exception in case this method is called

**Comment by enikao** [comment]
As LW-C# is open source now, you could have a look at the design there: We have `IReadableNode` as root of the inheritance hierarchy, then `IWritableNode`, and `INode` is essentially just an alias of `IWritableNode`.
Language entities extend e.g. `ConceptBase`, which only implements `IReadableNode`. All generated classes implement `INode`.

So, in a nutshell:

* `IReadableNode`
  * `ReadableNodeBase`
    * `ConceptBase`
      * `IKeyedBase`
        * `ClassifierBase`
          * `ConceptBase`
  * `IWritableNode`
    * `INode`
      * `NodeBase`
        * `MyGeneratedConceptClass`
