### ISSUE TITLE
LionCore-builtins.Node and INamed should be mapped to EClasses when instantiating an EMFModelExporter

### ISSUE THREAD

**Issue by AtanasM98** [LionWeb-io/lionweb-java#98]
We had to manually do this when trying to register a language file to EMF.

```
var ConceptsToEClassesMapping conceptMapper = new ConceptsToEClassesMapping();

conceptMapper.registerMapping(LionCoreBuiltins.getNode(), EcorePackage.eINSTANCE.getEObject())

val builtinsEPackage = EcoreFactory.eINSTANCE.createEPackage()
builtinsEPackage.name = "LionCore_builtins"
builtinsEPackage.nsURI = "LionCore-builtins"

val eCoreINamed = EcoreFactory.eINSTANCE.createEClass()
eCoreINamed.name = "INamed"
eCoreINamed.interface = true
builtinsEPackage.EClassifiers.add(eCoreINamed)

val eCoreINamedName = EcoreFactory.eINSTANCE.createEAttribute()
eCoreINamedName.name = "name"
eCoreINamedName.EType = EcorePackage.eINSTANCE.EString
eCoreINamed.EStructuralFeatures.add(eCoreINamedName)

conceptMapper.registerMapping(LionCoreBuiltins.getINamed(), eCoreINamed)
```

This should be preregistered since it's something every language is going to use.
You can see it in action in [my repository using EMF reflective access](https://github.com/f1re-nl/emf-gettingstarted/blob/main/nl.f1re.emf.generator.emf.reflective/src/main/java/nl/f1re/emf/generator/emf/reflective/EmfReflective.xtend).

**Comment by ftomassetti** [comment]
Right, they should. Perhaps we evolved LionCore builtins since we wrote the EMF mapping. Thank you for reporting this @AtanasM98

**Comment by AtanasM98** [comment]
This issue is also valid for EMFMetaModelExporter.
